### ISSUE TITLE
车车运行华住会和霸王茶姬各有一个错误

### ISSUE THREAD

**Issue by bandengzex** [checkToke/yangtai#10]
华住会错误
![图片](https://github.com/user-attachments/assets/64e1ee9e-9637-498a-b7b3-b25fe8ebca5e)
霸王茶姬错误
![图片](https://github.com/user-attachments/assets/3ddd5b51-29b9-47db-914d-27311cf57e56)
另外东呈会就是运行时错误
![图片](https://github.com/user-attachments/assets/b5cdb019-66d4-4a8d-b156-a2c28cb19231)

**Comment by checkToke** [comment]
霸王茶及的签到成功了 应该是查积分的时候网络超时了 我再试没有重现问题
华住会的你提交的url不对，不要只提交**的部分，是完整的url  带上**前面的
东呈会的也是一样的，不过我看东城会的没有提交上来 不确定是啥问题 不行邮箱发我url
tiankafeitian@gmail.com

**Comment by checkToke** [comment]
自动格式化了 不要只提交星星不分 是完整的url，包括星星前面的部分

**Comment by bandengzex** [comment]
好的  已修改提交成功
