### ISSUE TITLE
霸王茶姬G了

### ISSUE THREAD

**Issue by SugarCarry** [checkToke/yangtai#11]
大佬，霸王茶姬G了。。可修复么？

**Comment by checkToke** [comment]
看到了 签到接口加了签名 今天搞

**Comment by checkToke** [comment]
提交了 可以试试 ck需要token和userId，车车还没更新

**Comment by SugarCarry** [comment]
> 提交了 可以试试 ck需要token和userId，车车还没更新

这个userid是那个。名字就叫userid？？没找到。。只有appid，openid，unionid
