### ISSUE TITLE
一汽大众

### ISSUE THREAD

**Issue by 158668qq** [checkToke/yangtai#14]
一汽大众登陆失败

**Comment by checkToke** [comment]
我这里运行着没问题 提示啥？不行直接上车

**Comment by checkToke** [comment]
你的密码是不是有#号啊 改成没有#号的就行了

**Comment by RSKD-L** [comment]
> 你的密码是不是有#号啊 改成没有#号的就行了

一汽大众日常签到没积分，是风控了吗？

**Comment by checkToke** [comment]
![image](https://github.com/user-attachments/assets/e4211414-8843-4e39-8e2f-b15b2700154b)
签到接口失效了

**Comment by RSKD-L** [comment]
> ![image](https://private-user-images.githubusercontent.com/173645896/365518411-e4211414-8843-4e39-8e2f-b15b2700154b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NjU2NTcsIm5iZiI6MTcyNTg2NTM1NywicGF0aCI6Ii8xNzM2NDU4OTYvMzY1NTE4NDExLWU0MjExNDE0LTg4NDMtNGUzOS04ZTJmLWIxNWIyNzAwMTU0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwNzAyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjFlZDczNzU0MTZkMDA5YjhiNmNmYTFiZWY0OGM2OWM1MjJkZDlhNWJjNzdlNzcxNjgxODhiYjFlMTUyZjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iiAhJp5SyIs_F-1Pzk60VzCwMMoZfJEEamYnrjAhErc) 签到接口失效了

哦哦，看到了，谢谢，辛苦了
