### ISSUE TITLE
大佬，华住会好像失效了

### ISSUE THREAD

**Issue by QiHsMing** [checkToke/yangtai#15]
日志信息如下：
🔔华住会, 开始!
文件md5：bae990de2f8a47da70e954eacadaffee
是最新的版本，好样的
🧐215304301🧐
AxiosError: Request failed with status code 401

**Comment by checkToke** [comment]
![image](https://github.com/user-attachments/assets/b86a5ac5-584c-4f7a-b289-8dbdcf58f6cd)
脚本应该没问题 每天多跑几次吧，偶发性网络不好，如果还是不行 可以上车试试，还是有问题 给我说一下上车时间，我查一下

**Comment by checkToke** [comment]
脚本应该没问题 每天多跑几次吧，偶发性网络不好，如果还是不行 可以上车试试，还是有问题 给我说一下上车时间，我查一下
![image](https://github.com/user-attachments/assets/8f2b210a-7602-496b-8f11-2011277936e0)

**Comment by QiHsMing** [comment]
好的谢谢

**Comment by Martinxux** [comment]
大佬，我直接复制的文件，华住会检查版本失败了，这个是咋回事？
![PixPin_2024-11-27_15-48-27](https://github.com/user-attachments/assets/2d19eae7-9aa7-43f3-9d18-cb22dbd30a42)

**Comment by checkToke** [comment]
没事 虽然我也不知道你干啥了 能签到就没事
