### ISSUE TITLE
大佬们求助霸王茶姬抓不到userid怎么回事啊？空白的

### ISSUE THREAD

**Issue by 591047593** [checkToke/yangtai#16]
哪位大佬能帮忙解答下，感谢

**Comment by checkToke** [comment]
https://webapi2.qmai.cn/web/seller/oauth/flash-sale-login  把这个请求的响应发出来

**Comment by Gesch777** [comment]
> https://webapi2.qmai.cn/web/seller/oauth/flash-sale-login 把这个请求的响应发出来

![image](https://github.com/user-attachments/assets/b6a22d07-5707-4919-aefc-6106dbb66cd2)
![image](https://github.com/user-attachments/assets/f4facb0d-a983-4646-960d-d23c6e944adb)
![image](https://github.com/user-attachments/assets/7dc86cfe-de4c-404d-bab4-46164a002f62)
哥，帮我看看，我也没看到userid...

**Comment by Gesch777** [comment]
> https://webapi2.qmai.cn/web/seller/oauth/flash-sale-login 把这个请求的响应发出来

找到了哥，在har文件里面有
![image](https://github.com/user-attachments/assets/7ec5a966-0e3c-45d3-9bcc-37db134c5db1)
![image](https://github.com/user-attachments/assets/67a7e57d-220f-481f-9d85-4e65b35ea339)

**Comment by Gesch777** [comment]
![image](https://github.com/user-attachments/assets/28c076d8-0662-4965-971f-670373f33f2d)
ok了哥，又能签到卖券了，谢谢

**Comment by checkToke** [comment]
看看益和堂吧 新鲜出炉的 20天一杯免单卷（我自己算的）

**Comment by checkToke** [comment]
点个star吧 -_-

**Comment by Gesch777** [comment]
> 看看益和堂吧 新鲜出炉的 20天一杯免单卷（我自己算的）

好的哥

**Comment by Gesch777** [comment]
> 点个star吧 -_-

包点的

**Comment by Gesch777** [comment]
> 看看益和堂吧 新鲜出炉的 20天一杯免单卷（我自己算的）

哥，Qm-User-Token找不到
![image](https://github.com/user-attachments/assets/54a0eedf-bb6a-4d8f-88a6-8dbb04397f6b)

**Comment by checkToke** [comment]
除了这个别的都有。。换一个请求

**Comment by Gesch777** [comment]
> 除了这个别的都有。。换一个请求

没有哥，找不到，所有请求都看了一遍

**Comment by checkToke** [comment]
https://webapi.qmai.cn/web/cmk-center/task/taskInfo 搜这个 在请求头中

**Comment by Gesch777** [comment]
> https://webapi.qmai.cn/web/cmk-center/task/taskInfo 搜这个 在请求头中

有了哥，这抓包软件把webapi.qmai.cn过滤了，我说怎么一直抓不到，谢了哥

**Comment by 591047593** [comment]
感谢!  已解决
