### ISSUE TITLE
一汽大众登录失败

### ISSUE THREAD

**Issue by small-thunder** [checkToke/yangtai#17]
![image](https://github.com/user-attachments/assets/9e137879-4b80-4c08-8b83-aaf59824bce8)

**Comment by small-thunder** [comment]
这个did  应该就是 distinct_id  这个吧？

**Comment by checkToke** [comment]
yqdz_Did 是请求头中的 Did
一汽大众签到失效了 刚发现 待修

**Comment by small-thunder** [comment]
> yqdz_Did 是请求头中的 Did 一汽大众签到失效了 刚发现 待修

好的  大佬

**Comment by checkToke** [comment]
上益和堂 一个号20天一杯奶茶

**Comment by small-thunder** [comment]
> 上益和堂 一个号20天一杯奶茶

附近没有益禾堂...

**Comment by checkToke** [comment]
-_-

**Comment by small-thunder** [comment]
> 大佬可以建个交流群

大佬建个交流群吧
