### ISSUE TITLE
青龙运行万达酒店报错

### ISSUE THREAD

**Issue by 51Hertz** [checkToke/yangtai#18]
ProtocolError: Network.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
TypeError: Cannot read properties of undefined (reading 'length')

大佬这个知道怎么解决吗

**Comment by checkToke** [comment]
上车吧 告诉我上车时间
现在万达酒店还在测试中，有掉登陆状态的问题

**Comment by checkToke** [comment]
废了 凉凉了

**Comment by 51Hertz** [comment]
哈哈 尴尬了 怎么了 加密了吗

**Comment by checkToke** [comment]
如果只是加密没关系 现在它是走了微信的加密通道 搞不了

**Comment by checkToke** [comment]
要是能找到其他可以签到万达酒店的本 给我说一下 我看看咋实现的 我觉得不可能破解得了

**Comment by 51Hertz** [comment]
哈哈 好的
