### ISSUE TITLE
挂代理显示这个运行霸王茶姬时显示以下代码，不挂代理库更新不了

### ISSUE THREAD

**Issue by 642532014** [checkToke/yangtai#20]
Error: Client network socket disconnected before secure TLS connection was established

这是什么原因啊

**Comment by checkToke** [comment]
你是说拉库有问题么？如果是拉库的话，那就是你所在地区网络github dns污染

**Comment by checkToke** [comment]
拉库需要挂代理才稳定

**Comment by 642532014** [comment]
拉库我正常挂了代理正常拉取，可是挂了代理霸王茶姬运行就是这段错误日志
Error: Client network socket disconnected before secure TLS connection was established

**Comment by checkToke** [comment]
我也解释不了。。不行上车吧
![image](https://github.com/user-attachments/assets/7763d173-33ba-4df3-9c26-dae8030fb24a)

**Comment by SugarCarry** [comment]
醉了，。昨天一天漏看了，更新了，。依赖没安装。。好容易跑了23天了，，又g了。。。三个月了。。没一次30天的，不是这问题就是那问题。。。

**Comment by checkToke** [comment]
弄个通知吧 如果是ios 推荐bark 超级好用

**Comment by checkToke** [comment]
建议你上车跑着 自己也跑着。。。
