### ISSUE TITLE
霸王茶几抓包

### ISSUE THREAD

**Issue by 6pjj6** [checkToke/yangtai#22]
霸王茶几是不是改了，没抓到https://webapi2.qmai.cn/web下的seller
![image](https://github.com/user-attachments/assets/8755340a-9147-4ba8-90f1-c7e506e2d6bf)

**Comment by checkToke** [comment]
登录的时候才会有 把小程序删除了 重新进小程序 进入小程序的时候抓包

**Comment by 6pjj6** [comment]
> 登录的时候才会有 把小程序删除了 重新进小程序 进入小程序的时候抓包

我抓了别的，也可以跑起来，就是不知道时效性怎么样，感谢

**Comment by checkToke** [comment]
嗯嗯 应该都是一样的
