### ISSUE TITLE
霸王茶姬ip问题

### ISSUE THREAD

**Issue by 957355295** [checkToke/yangtai#23]
霸王能内置一下ip调用吗，然后代理用我们自己的，设置一个自定义ip的位置
![1726846522978](https://github.com/user-attachments/assets/e0d5f33f-5684-4d6d-85fa-c0b32d92744c)
![1726846372640](https://github.com/user-attachments/assets/f8ea8360-c878-40cf-ae5b-10399d3e76c9)
![1726846649014](https://github.com/user-attachments/assets/8c023623-6985-45c4-89ba-8afe81ca5c5e)
您看一下，代码和效果图发给您了，这是别人本子的效果，麻烦了

**Comment by checkToke** [comment]
有点没时间搞唉 你这个代理是谁家的？是要请求一个api 给你返回来一堆代理么
