### ISSUE TITLE
华住会怎么获取

### ISSUE THREAD

**Issue by chuanleliu** [checkToke/yangtai#25]

**Comment by checkToke** [comment]
路径： 会员 -> 签到   抓点击签到后的完整url 例：https://hweb-minilogin.huazhu.com/bridge/jump?redirectUrl=*********

**Comment by chuanleliu** [comment]
<img width="638" alt="error" src="https://github.com/user-attachments/assets/da423bfe-648c-4492-a28c-590e8978c309">

**Comment by chuanleliu** [comment]
<img width="177" alt="hzh" src="https://github.com/user-attachments/assets/2cd61ad1-63c8-49bc-bf61-0818df4171d2">
<img width="311" alt="error" src="https://github.com/user-attachments/assets/dccb0bfe-cf0c-4f5f-9745-90ccd422b3bf">
添加方式不对？

**Comment by checkToke** [comment]
要在环境变量加

**Comment by checkToke** [comment]
![image](https://github.com/user-attachments/assets/d7ed0fc8-994d-49ce-897a-36df30810b76)

**Comment by chuanleliu** [comment]
<img width="481" alt="ylai" src="https://github.com/user-attachments/assets/ed48ccc6-68f3-4b52-9e3a-af161f736d78">
<img width="343" alt="error" src="https://github.com/user-attachments/assets/2018fdb3-927e-45c0-8034-d30c0b1630ec">
<img width="693" alt="jb" src="https://github.com/user-attachments/assets/dce1bf8e-2b12-4c21-8bc4-63d4977b1917">
<img width="535" alt="hzh" src="https://github.com/user-attachments/assets/a5fc3fd2-d4f0-43f9-98da-27c52db42997">
您好，为什么我自建的会报这个错误，代码是新拉下来的

**Comment by chuanleliu** [comment]
<img width="693" alt="jb" src="https://github.com/user-attachments/assets/054e7189-e130-4b3f-9796-e4ec7abc4faf">
<img width="535" alt="hzh" src="https://github.com/user-attachments/assets/e6dc2fa4-1b98-4219-b770-9f819dad2448">
<img width="481" alt="ylai" src="https://github.com/user-attachments/assets/e2cbd22b-3151-46cf-ac97-7c5667b62cbc">
<img width="343" alt="error" src="https://github.com/user-attachments/assets/b5abc483-1899-47ca-863a-4180efe84c9d">


您好，为什么我自建的会报这个错误？

**Comment by checkToke** [comment]
重新拉下脚本呢 看着脚本有问题 我试了下我这里不报错
你这个看着是脚本自身有错误
