### ISSUE TITLE
霸王茶姬好像挂了

### ISSUE THREAD

**Issue by Gesch777** [checkToke/yangtai#28]
![image](https://github.com/user-attachments/assets/e1b4c88f-8c50-4aa5-ac5f-91943c10a1b9)
签到28天漏了一天，555555，大佬看一下呗

**Comment by Gesch777** [comment]
重新抓了也没用...

**Comment by checkToke** [comment]
你的userId抓的不对哦

**Comment by Gesch777** [comment]
![image](https://github.com/user-attachments/assets/fa9ab32c-b6ee-496d-8d6d-1854e5aa5789)
不是这个吗，哥

**Comment by Gesch777** [comment]
![image](https://github.com/user-attachments/assets/54a9f89f-39de-4992-8962-07b2af6c0de3)
用了上面那个请求里的token和userid能签到了，之前都是抓下面那个请求的.....

**Comment by checkToke** [comment]
没见过上面的那个请求。。

**Comment by checkToke** [comment]
是的 估计要凉凉了
