### ISSUE TITLE
求增加【华住会】【东呈会】【长安汽车】为感！ 

### ISSUE THREAD

**Issue by bandengzex** [checkToke/yangtai#3]
前两个积分可以酒店抵房费，后一个积分可以换QQ音乐会员

**Comment by checkToke** [comment]
![image](https://github.com/user-attachments/assets/4df778f6-a247-4b3c-9dcb-22cd8b092706)
提供下华住会小程序跳转到签到页面的完整url 开头是：https://hweb-minilogin.huazhu.com/bridge/jump 我这个账号不能签到,没办法调试邮箱：tiankafeitian@gmail.com

**Comment by bandengzex** [comment]
我用小程序F12工具抓到的包似乎没有https://hweb-minilogin.huazhu.com/bridge/jump 开头的链接。请问您是用什么工具进行抓包抓到的这个呀

> ![image](https://private-user-images.githubusercontent.com/173645896/351551427-4df778f6-a247-4b3c-9dcb-22cd8b092706.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDI3NTAsIm5iZiI6MTcyMTgwMjQ1MCwicGF0aCI6Ii8xNzM2NDU4OTYvMzUxNTUxNDI3LTRkZjc3OGY2LWEyNDctNGIzYy05ZGNiLTIyY2Q4YjA5MjcwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwNjI3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGJhNjExNDVjZDgxYTczMGU5YTUzYzc5ZTBjM2QyYWJjM2U4Y2ZjNWZiMTM5YTE3YjAyNTMxZjJmYmUxZjA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x-BAklEeH7AKXo9M2CwIISyvLJLq5iWd_77VFlzWgLc) 提供下华住会小程序跳转到签到页面的完整url 开头是：https://hweb-minilogin.huazhu.com/bridge/jump 我这个账号不能签到,没办法调试邮箱：[tiankafeitian@gmail.com](mailto:tiankafeitian@gmail.com)

**Comment by bandengzex** [comment]
另外我无意发现了华住会网页版的签到链接https://campaign.huazhu.com/pointsShop/index.html?source=signintop#/signIn

**Comment by checkToke** [comment]
落地页是https://campaign.huazhu.com/pointsShop/index.html?source=signintop#/signIn
有个中间授权页跳转
小程序：华住会酒店预订汉庭全季桔子
路径：会员 -> 签到

**Comment by checkToke** [comment]
> 另外我无意发现了华住会网页版的签到链接https://campaign.huazhu.com/pointsShop/index.html?source=signintop#/signIn



> 我用小程序F12工具抓到的包似乎没有https://hweb-minilogin.huazhu.com/bridge/jump 开头的链接。请问您是用什么工具进行抓包抓到的这个呀
> 
> > ![image](https://private-user-images.githubusercontent.com/173645896/351551427-4df778f6-a247-4b3c-9dcb-22cd8b092706.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDI3NTAsIm5iZiI6MTcyMTgwMjQ1MCwicGF0aCI6Ii8xNzM2NDU4OTYvMzUxNTUxNDI3LTRkZjc3OGY2LWEyNDctNGIzYy05ZGNiLTIyY2Q4YjA5MjcwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwNjI3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGJhNjExNDVjZDgxYTczMGU5YTUzYzc5ZTBjM2QyYWJjM2U4Y2ZjNWZiMTM5YTE3YjAyNTMxZjJmYmUxZjA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x-BAklEeH7AKXo9M2CwIISyvLJLq5iWd_77VFlzWgLc) 提供下华住会小程序跳转到签到页面的完整url 开头是：https://hweb-minilogin.huazhu.com/bridge/jump 我这个账号不能签到,没办法调试邮箱：[tiankafeitian@gmail.com](mailto:tiankafeitian@gmail.com)

是个文档跳转 不是xhr

**Comment by bandengzex** [comment]
> > 另外我无意发现了华住会网页版的签到链接https://campaign.huazhu.com/pointsShop/index.html?source=signintop#/signIn
> 
> > 我用小程序F12工具抓到的包似乎没有https://hweb-minilogin.huazhu.com/bridge/jump 开头的链接。请问您是用什么工具进行抓包抓到的这个呀
> > > ![image](https://private-user-images.githubusercontent.com/173645896/351551427-4df778f6-a247-4b3c-9dcb-22cd8b092706.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDI3NTAsIm5iZiI6MTcyMTgwMjQ1MCwicGF0aCI6Ii8xNzM2NDU4OTYvMzUxNTUxNDI3LTRkZjc3OGY2LWEyNDctNGIzYy05ZGNiLTIyY2Q4YjA5MjcwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwNjI3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGJhNjExNDVjZDgxYTczMGU5YTUzYzc5ZTBjM2QyYWJjM2U4Y2ZjNWZiMTM5YTE3YjAyNTMxZjJmYmUxZjA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x-BAklEeH7AKXo9M2CwIISyvLJLq5iWd_77VFlzWgLc) 提供下华住会小程序跳转到签到页面的完整url 开头是：https://hweb-minilogin.huazhu.com/bridge/jump 我这个账号不能签到,没办法调试邮箱：[tiankafeitian@gmail.com](mailto:tiankafeitian@gmail.com)
> 
> 是个文档跳转 不是xhr

已发送，您看下是否是

**Comment by checkToke** [comment]
东呈会提交了 挂着试试
华住会我看今天签到没有成功，明天我再调试下，你先别手动签到呢

**Comment by bandengzex** [comment]
> 东呈会提交了 挂着试试 华住会我看今天签到没有成功，明天我再调试下，你先别手动签到呢

我看了下华住会签到成功了，可能成功了回调不对吧

**Comment by bandengzex** [comment]
![图片](https://github.com/user-attachments/assets/b63416fe-02ac-42d6-a018-3c1f2d6803d5)
我尝试了好几次，换了服务器还是这个错误。问了下AI是不是你代码里要链接本地地址的80端口呀

**Comment by checkToke** [comment]
我也看不出来啥子问题 等我弄个上车功能吧 直接代挂吧

**Comment by checkToke** [comment]
上车 链接：https://checktoke.filegear-sg.me/bus 日志正常即上车成功，不要重复提交
