### ISSUE TITLE
益禾堂助力

### ISSUE THREAD

**Issue by LY-Serase** [checkToke/yangtai#30]
大佬，能不能出一个本地助力版本的，填变量的那种

**Comment by checkToke** [comment]
脚本都黄了

**Comment by checkToke** [comment]
不行了吧 你的ck不会掉吗 现在几个小时就掉了

**Comment by checkToke** [comment]
在前天之前 每个人的号基本都是满助力的，现在因为ck都掉了 所以没有助力了

**Comment by Gesch777** [comment]
建议清空一波助力码，让每天进一下小程序的人能有助力

**Comment by checkToke** [comment]
清了10月1号之前的助力码了，脚本支持优先助力自己的助力码
