### ISSUE TITLE
霸王茶姬

### ISSUE THREAD

**Issue by linxi6** [checkToke/yangtai#33]
这是怎么回事？![Screenshot_2024-10-21-00-54-31-986_work.master.qinglongapp.jpg](https://github.com/user-attachments/assets/26933e6f-860d-454e-845f-858ce537c072)

**Comment by checkToke** [comment]
userid不对

**Comment by linxi6** [comment]
"loginToken": {            "user": {                "id":

**Comment by linxi6** [comment]
"loginToken": {            "user": {                "id":

**Comment by linxi6** [comment]
> userid不对

我填的userid是https://webapi2.qmai.cn/web/seller/user/bind-mobile-by-wechat返回中的这个
   "loginToken": {           
 "user": { 
               "id": xxxxx

**Comment by linxi6** [comment]
> userid不对

重新抓了一个token又行了
