### ISSUE TITLE
在新增的华住会脚本中提示了连接报错

### ISSUE THREAD

**Issue by bandengzex** [checkToke/yangtai#4]
我分别在Linux服务器和windows本地docker运行都出现了报错
**以下是本地docker运行报错**
![图片](https://github.com/user-attachments/assets/c8a349ba-21cb-4aab-aa66-c63cdebb1fcf)

**以下是服务器上运行报错**
![图片](https://github.com/user-attachments/assets/4c8c1757-9e16-4812-8f7d-56ec2d96aea0)

**Comment by checkToke** [comment]
![image](https://github.com/user-attachments/assets/6f8b29dd-ff61-4587-b92a-033df2f6c871)
感觉你好像走了代理？

**Comment by bandengzex** [comment]
> ![image](https://private-user-images.githubusercontent.com/173645896/352031933-6f8b29dd-ff61-4587-b92a-033df2f6c871.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDAzNjAsIm5iZiI6MTcyMTkwMDA2MCwicGF0aCI6Ii8xNzM2NDU4OTYvMzUyMDMxOTMzLTZmOGIyOWRkLWZmNjEtNDU4Ny1iOTJhLTAzM2RmMmY2Yzg3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwOTM0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjQxMWU1ZjM1YTQ3Mjc5ZGQ5Njg5ODNlM2U1ZDA5N2MxNDE0YzYzYzU2MDUxZjI3NmQ2OTM3ZmU0ZDAxNjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yxJUIIH6tUUr0OT6lNHOTEdgPFEBupmuiSq5TMLpSFQ) 感觉你好像走了代理？

本地是挂了DNS，虽然不知道会不会有影响，但是京东类是可以正常运行的。服务器上我看了下没有代理呀

**Comment by bandengzex** [comment]
![图片](https://github.com/user-attachments/assets/d01ce54a-1995-47e3-9010-3b072cc7ca13)
axios-cookiejar-support这个依赖的问题么？

**Comment by checkToke** [comment]
好高级哎 不太懂。。。。
