### ISSUE TITLE
投稿 霸王社群签到25天买一送一

### ISSUE THREAD

**Issue by huzi068** [checkToke/yangtai#40]
这是活动入口 ![cff57d4bef361115669cc28dc253296](https://github.com/user-attachments/assets/cc827b37-f91f-4079-b19b-a330e777400e)

![0044b2d82c57b24b48b637916805a68](https://github.com/user-attachments/assets/ce8005c7-3e3e-40c9-aa5f-a97ce65fd63c)

**Comment by checkToke** [comment]
扫码进不去哇。。不允许分享

**Comment by huzi068** [comment]
> 扫码进不去哇。。不允许分享
企业微信社群 发布的省内/全国 当月签到活动 群里发布
本月的 https://3ct.cc/qXZAc85A

手机可以打开
从小程序主页找不到签到入口，只有在企业微信社群里面管理员发布的时候才能看到新的一个月链接

**Comment by checkToke** [comment]
https://3ct.cc/qXZAc85A  提示活动已结束
