### ISSUE TITLE
巴奴签到能弄吗

### ISSUE THREAD

**Issue by Wangsong-pe** [checkToke/yangtai#44]

**Comment by checkToke** [comment]
我瞧瞧

**Comment by checkToke** [comment]
一次消费可以使用多张积分兑换的卷么？

**Comment by Wangsong-pe** [comment]
> 一次消费可以使用多张积分兑换的卷么？

可以

**Comment by checkToke** [comment]
有些复杂 加密的地方有三个 并且没啥时间 再等等吧

**Comment by checkToke** [comment]
提交了

**Comment by Wangsong-pe** [comment]
已经用上了，谢谢老哥



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月13日 13:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [checkToke/yangtai] 巴奴签到能弄吗 (Issue #44) |

提交了

**Comment by killer3210** [comment]
> 已经用上了，谢谢老哥
> […](#)
> 
> ---- 回复的原邮件 ----
> | 发件人 | ***@***.***> |
> | 日期 | 2024年12月13日 13:57 |
> | 收件人 | ***@***.***> |
> | 抄送至 | ***@***.***>***@***.***> |
> | 主题 | Re: [checkToke/yangtai] 巴奴签到能弄吗 (Issue [#44](https://github.com/checkToke/yangtai/issues/44)) |
> 
> 提交了
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

你现在能正常跑吗请问
