### ISSUE TITLE
益禾堂已上加密

### ISSUE THREAD

**Issue by catsimple** [checkToke/yangtai#46]
![image](https://github.com/user-attachments/assets/d9a32708-6a07-4d37-af32-bba338c4638c)

霸王茶姬同款

**Comment by checkToke** [comment]
你是通过pc 打开调试的是么？

**Comment by checkToke** [comment]
哪里加密了？我咋没找到嘞？

**Comment by Stonedragon3** [comment]
解出来了吗，看得脑瓜疼

**Comment by catsimple** [comment]
> 解出来了吗，看得脑瓜疼

解啥啊，微信官方的接口，基本上算废了。

**Comment by Stonedragon3** [comment]
我说在里面咋找不到呢，第一次解就解这个，一直找不到

**Comment by checkToke** [comment]
解不了 废了
